### ISSUE TITLE
Allow users to set `summary metric` column and `floor` in configuration

### ISSUE THREAD

**Issue by jbloom** [dms-viz/configure_dms_viz#31]
Is there a way to set the *summary metric* and *floor* options when configuring? If so, this isn't documented.

**Comment by WillHannon-MCB** [comment]
There isn't. These are saved in the URL address if you're sharing a link. Should I add an option to set these while configuring?

**Comment by jbloom** [comment]
That would be awesome if it is feasible to add them.

**Comment by WillHannon-MCB** [comment]
It's feasible! I'll add them.

**Comment by jbloom** [comment]
These seem to be added via the `--floor` and `--summary-stat` parameters, but this is not documented. Can it be added to the documentation before this issue is closed.

**Comment by WillHannon-MCB** [comment]
[It's documented](https://dms-viz.github.io/dms-viz-docs/preparing-data/command-line-api/#floor).

**Comment by jbloom** [comment]
@WillHannon-MCB, although these work in `configure-dms-viz format`, when different JSONs are joined with `configure-dms-viz join` then the dataset-specific configurations are lost. Can they be retained for different datasets after joining?

**Comment by WillHannon-MCB** [comment]
This sounds like a bug in my implementation. Can you post the individual and joined JSON files?

**Comment by jbloom** [comment]
Joined file and one of the constituents.
[stability.json](https://github.com/dms-viz/configure_dms_viz/files/15396413/stability.json)


[dms-viz.json](https://github.com/dms-viz/configure_dms_viz/files/15396412/dms-viz.json)

**Comment by WillHannon-MCB** [comment]
This isn't exactly a bug. The options selected in the menu persist when the visualization changes so that you can compare datasets without re-configuring the options each time. Since the first dataset in `dms-viz.json` sets `floor` to `false`, that value persists even when you change to a new dataset.

I opened [an issue](https://github.com/dms-viz/dms-viz.github.io/issues/89) to address this by giving values in the configuration precedence over the menu selection when the dataset changes. I'm closing this issue since it's not a problem with `configure-dms-viz`.
